#!/bin/bash

# This script sets up the vagrant box when it boots up for the first time. 

cd $(dirname "$0")
SCRIPTDIR=$(pwd)

cat > /etc/apt/sources.list.d/multiverse.list <<EOF
# Enable the "multiverse" repository.  mod_fastcgi is there. 
deb http://archive.ubuntu.com/ubuntu trusty multiverse
deb-src http://archive.ubuntu.com/ubuntu trusty multiverse
deb http://archive.ubuntu.com/ubuntu trusty-updates multiverse
deb-src http://archive.ubuntu.com/ubuntu trusty-updates multiverse
EOF

# Install dmd, dub, and mod-fcgid:
# See: http://d-apt.sourceforge.net/
wget http://master.dl.sourceforge.net/project/d-apt/files/d-apt.list -O /etc/apt/sources.list.d/d-apt.list
apt-get update -q
apt-get -y --allow-unauthenticated install --reinstall d-apt-keyring
# Is this strictly necessary?
apt-get update -q

# Lock down dmd & dub versions. Dub currently broken w/ dmd 2067. :( 
apt-get install -y dmd-bin=2.066.1-0 libphobos2-dev=2.066.1-0 dub=0.9.22-0 apache2 libapache2-mod-fastcgi

# Try to build the sample application: 
su vagrant -c "/bin/bash ./redeploy_sample"


