#!/bin/bash

# This script sets up the vagrant box when it boots up for the first time. 

cd $(dirname "$0")
SCRIPTDIR=$(pwd)


# Install dmd, dub, and mod-fcgid:
# See: http://d-apt.sourceforge.net/
wget http://master.dl.sourceforge.net/project/d-apt/files/d-apt.list -O /etc/apt/sources.list.d/d-apt.list
apt-get update
apt-get -y --allow-unauthenticated install --reinstall d-apt-keyring
# Is this strictly necessary?
apt-get update
apt-get install -y dmd-bin dub apache2 libapache2-mod-fcgid

# Try to build the sample application: 
su vagrant -c "/bin/bash ./redeploy_sample"


